name: 'Pandoc Document Converter'
description: 'Convert documents using Pandoc'
inputs:
  source:
    description: 'Source file(s) to convert (glob patterns supported)'
    required: true
  output-format:
    description: 'Target format (pdf, docx, html, etc.)'
    required: true
    default: 'html'
  output-dir:
    description: 'Directory where converted files should be placed'
    required: false
    default: 'output'
  template:
    description: 'Optional template file'
    required: false
  extra-args:
    description: 'Additional pandoc arguments'
    required: false
runs:
  using: 'docker'
  image: 'docker://pandoc/latex:latest'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      set -e
      
      # Create output directory if it doesn't exist
      mkdir -p "${{ inputs.output-dir }}"
      
      # Process template option
      TEMPLATE_ARG=""
      if [ -n "${{ inputs.template }}" ]; then
        TEMPLATE_ARG="--template=${{ inputs.template }}"
      fi
      
      # Find and process all source files
      for source_file in ${{ inputs.source }}; do
        if [ -f "$source_file" ]; then
          filename=$(basename -- "$source_file")
          extension="${filename##*.}"
          filename="${filename%.*}"
          
          output_file="${{ inputs.output-dir }}/${filename}.${{ inputs.output-format }}"
          
          echo "Converting $source_file to $output_file"
          
          # Execute pandoc with the specified options
          pandoc "$source_file" -o "$output_file" $TEMPLATE_ARG ${{ inputs.extra-args }}
          
          echo "Conversion complete: $output_file"
        fi
      done